services:
  product-service:
    build: .
    container_name: product-service
    ports:
      - "8000:8000"
    networks:
      - restaurant-network

networks:
  restaurant-network:
    name: restaurant-network